-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.client_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  label text NOT NULL,
  street_address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  zip_code text NOT NULL,
  country text DEFAULT 'United States'::text,
  is_default boolean DEFAULT false,
  is_pickup_location boolean DEFAULT true,
  is_delivery_location boolean DEFAULT true,
  contact_name text,
  contact_phone text,
  special_instructions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT client_addresses_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.client_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['credit_card'::text, 'debit_card'::text, 'bank_account'::text, 'paypal'::text])),
  provider text NOT NULL,
  provider_payment_method_id text NOT NULL,
  last_four text,
  card_brand text,
  expiry_month integer,
  expiry_year integer,
  is_default boolean DEFAULT false,
  billing_address jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT client_payment_methods_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.client_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL UNIQUE,
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  marketing_emails boolean DEFAULT false,
  auto_quotes boolean DEFAULT true,
  preferred_communication text DEFAULT 'email'::text CHECK (preferred_communication = ANY (ARRAY['email'::text, 'sms'::text, 'push'::text])),
  quote_notifications boolean DEFAULT true,
  shipment_updates boolean DEFAULT true,
  promotional_offers boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_settings_pkey PRIMARY KEY (id),
  CONSTRAINT client_settings_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT conversations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT conversations_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  vehicle_type USER-DEFINED NOT NULL,
  vehicle_make text NOT NULL,
  vehicle_model text NOT NULL,
  vehicle_year integer NOT NULL CHECK (vehicle_year > 1900 AND vehicle_year::numeric <= (EXTRACT(year FROM now()) + 1::numeric)),
  license_number text NOT NULL,
  license_expiry date NOT NULL,
  insurance_provider text NOT NULL,
  insurance_policy_number text NOT NULL,
  insurance_expiry date NOT NULL,
  background_check_status text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT driver_applications_pkey PRIMARY KEY (id),
  CONSTRAINT driver_applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  heading double precision,
  speed double precision,
  accuracy double precision,
  location_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT driver_locations_pkey PRIMARY KEY (id),
  CONSTRAINT driver_locations_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT driver_locations_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_privacy_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL UNIQUE,
  share_location_with_customers boolean DEFAULT true,
  share_phone_with_customers boolean DEFAULT false,
  allow_rating_and_reviews boolean DEFAULT true,
  data_retention_period text DEFAULT '2years'::text CHECK (data_retention_period = ANY (ARRAY['1year'::text, '2years'::text, '5years'::text, 'indefinite'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_privacy_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT driver_privacy_preferences_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.driver_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL UNIQUE,
  driver_id uuid NOT NULL,
  client_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT driver_ratings_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT driver_ratings_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT driver_ratings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_security_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL UNIQUE,
  two_factor_enabled boolean DEFAULT false,
  biometric_enabled boolean DEFAULT false,
  location_sharing_enabled boolean DEFAULT true,
  data_analytics_enabled boolean DEFAULT true,
  marketing_emails_enabled boolean DEFAULT false,
  push_notifications_enabled boolean DEFAULT true,
  emergency_contacts_enabled boolean DEFAULT true,
  trip_history_visibility text DEFAULT 'limited'::text CHECK (trip_history_visibility = ANY (ARRAY['public'::text, 'limited'::text, 'private'::text])),
  profile_visibility text DEFAULT 'limited'::text CHECK (profile_visibility = ANY (ARRAY['public'::text, 'limited'::text, 'private'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_security_settings_pkey PRIMARY KEY (id),
  CONSTRAINT driver_security_settings_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.driver_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL UNIQUE,
  available_for_jobs boolean DEFAULT true,
  notifications_enabled boolean DEFAULT true,
  preferred_radius integer DEFAULT 50,
  allow_location_tracking boolean DEFAULT true,
  preferred_job_types ARRAY DEFAULT ARRAY['standard'::text, 'express'::text],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_settings_pkey PRIMARY KEY (id),
  CONSTRAINT driver_settings_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  make text NOT NULL,
  model text NOT NULL,
  year integer NOT NULL,
  color text NOT NULL,
  license_plate text NOT NULL,
  vehicle_type text DEFAULT 'standard'::text CHECK (vehicle_type = ANY (ARRAY['standard'::text, 'large'::text, 'refrigerated'::text, 'hazmat'::text])),
  capacity_weight numeric,
  capacity_volume numeric,
  insurance_provider text,
  insurance_policy_number text,
  insurance_expiry_date date,
  registration_number text,
  registration_expiry_date date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT driver_vehicles_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.job_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])),
  applied_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_applications_pkey PRIMARY KEY (id),
  CONSTRAINT job_applications_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT job_applications_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  content text NOT NULL CHECK (char_length(TRIM(BOTH FROM content)) > 0),
  message_type text NOT NULL DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'system'::text, 'notification'::text])),
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
  CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  push_enabled boolean NOT NULL DEFAULT true,
  email_enabled boolean NOT NULL DEFAULT true,
  sms_enabled boolean NOT NULL DEFAULT false,
  shipment_updates boolean NOT NULL DEFAULT true,
  driver_assigned boolean NOT NULL DEFAULT true,
  payment_updates boolean NOT NULL DEFAULT true,
  promotions boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  client_id uuid NOT NULL,
  amount numeric NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  payment_method text,
  payment_intent_id text,
  payment_intent_client_secret text,
  refund_id text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  initial_amount integer,
  remaining_amount integer,
  booking_timestamp timestamp with time zone,
  refund_deadline timestamp with time zone,
  is_refundable boolean DEFAULT true,
  payment_type character varying DEFAULT 'initial'::character varying,
  parent_payment_id uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_parent_payment_id_fkey FOREIGN KEY (parent_payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text,
  avatar_url text,
  role USER-DEFINED NOT NULL DEFAULT 'client'::user_role,
  is_verified boolean NOT NULL DEFAULT false,
  rating numeric CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.push_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token text NOT NULL,
  device_type text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.shipment_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  status USER-DEFINED NOT NULL,
  changed_by uuid NOT NULL,
  changed_at timestamp with time zone DEFAULT now(),
  notes text,
  location_lat numeric,
  location_lng numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipment_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_status_history_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT shipment_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.shipments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  driver_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::shipment_status,
  title text NOT NULL,
  description text,
  pickup_address text NOT NULL,
  pickup_location USER-DEFINED,
  pickup_notes text,
  pickup_time_window tstzrange,
  delivery_address text NOT NULL,
  delivery_location USER-DEFINED,
  delivery_notes text,
  delivery_time_window tstzrange,
  weight_kg numeric,
  dimensions_cm jsonb,
  item_value numeric,
  is_fragile boolean DEFAULT false,
  estimated_distance_km numeric,
  estimated_price numeric NOT NULL,
  final_price numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  pickup_date timestamp with time zone,
  delivery_date timestamp with time zone,
  pickup_city text,
  pickup_state text,
  pickup_zip text,
  delivery_city text,
  delivery_state text,
  delivery_zip text,
  vehicle_type text,
  cargo_type text,
  distance numeric,
  price numeric,
  weight numeric,
  dimensions text,
  updated_by uuid,
  payment_status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  vehicle_make text,
  vehicle_model text,
  vehicle_year integer,
  is_operable boolean DEFAULT true,
  payment_intent_id text,
  terms_accepted boolean DEFAULT false,
  vehicle_count integer DEFAULT 1,
  is_accident_recovery boolean DEFAULT false,
  CONSTRAINT shipments_pkey PRIMARY KEY (id),
  CONSTRAINT shipments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT shipments_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT shipments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['technical'::text, 'account'::text, 'payment'::text, 'general'::text])),
  priority text NOT NULL CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tracking_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  event_type USER-DEFINED NOT NULL,
  created_by uuid NOT NULL,
  location USER-DEFINED,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracking_events_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_events_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT tracking_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_vehicles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  vehicle_type USER-DEFINED NOT NULL,
  make text NOT NULL,
  model text NOT NULL,
  year integer NOT NULL CHECK (year >= 1900 AND year::numeric <= (EXTRACT(year FROM now()) + 2::numeric)),
  color text,
  license_plate text CHECK (license_plate IS NULL OR length(license_plate) >= 2 AND length(license_plate) <= 15),
  nickname text,
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT user_vehicles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.vehicle_photos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  driver_application_id uuid NOT NULL,
  photo_url text NOT NULL,
  photo_type text NOT NULL,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_photos_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_photos_driver_application_id_fkey FOREIGN KEY (driver_application_id) REFERENCES public.driver_applications(id)
);