[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**/*"]

[deploy]
startCommand = "npm run railway:start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
rootDirectory = "backend"

[env]
PORT = "8080"
NODE_ENV = "production"
