[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm install && npm run build && node -r tsconfig-paths/register dist/index.js"
root = "backend"

[env]
PORT = "8080"
NODE_ENV = "production"
