-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.broker_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL UNIQUE,
  broker_id uuid NOT NULL,
  carrier_id uuid,
  broker_carrier_relationship_id uuid,
  assignment_status text DEFAULT 'pending'::text CHECK (assignment_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  assignment_type text NOT NULL CHECK (assignment_type = ANY (ARRAY['direct'::text, 'load_board_bid'::text])),
  assigned_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  total_amount numeric NOT NULL,
  carrier_payout numeric NOT NULL,
  broker_commission numeric NOT NULL,
  platform_fee numeric NOT NULL,
  commission_rate numeric NOT NULL,
  platform_fee_rate numeric NOT NULL,
  pickup_on_time boolean,
  delivery_on_time boolean,
  customer_rating integer CHECK (customer_rating >= 1 AND customer_rating <= 5),
  customer_feedback text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT broker_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT broker_assignments_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT broker_assignments_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.broker_profiles(id),
  CONSTRAINT broker_assignments_carrier_id_fkey FOREIGN KEY (carrier_id) REFERENCES public.profiles(id),
  CONSTRAINT broker_assignments_broker_carrier_relationship_id_fkey FOREIGN KEY (broker_carrier_relationship_id) REFERENCES public.broker_carriers(id)
);
CREATE TABLE public.broker_carriers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  broker_id uuid NOT NULL,
  carrier_id uuid NOT NULL,
  relationship_status text DEFAULT 'pending'::text CHECK (relationship_status = ANY (ARRAY['pending'::text, 'active'::text, 'inactive'::text, 'suspended'::text, 'terminated'::text])),
  invited_by text,
  invitation_accepted_at timestamp with time zone,
  commission_rate numeric NOT NULL,
  payment_terms text,
  total_shipments_completed integer DEFAULT 0,
  total_revenue_generated numeric DEFAULT 0,
  average_rating numeric DEFAULT 0,
  on_time_delivery_rate numeric DEFAULT 0,
  last_shipment_date timestamp with time zone,
  notes text,
  termination_reason text,
  terminated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT broker_carriers_pkey PRIMARY KEY (id),
  CONSTRAINT broker_carriers_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.broker_profiles(id),
  CONSTRAINT broker_carriers_carrier_id_fkey FOREIGN KEY (carrier_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.broker_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  broker_id uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['dot_authority'::text, 'mc_authority'::text, 'insurance_certificate'::text, 'surety_bond'::text, 'business_license'::text, 'tax_document'::text, 'fmcsa_license'::text, 'other'::text])),
  document_name text NOT NULL,
  description text,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size integer,
  mime_type text,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])),
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  expiry_date date,
  expiry_reminder_sent boolean DEFAULT false,
  is_expired boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT broker_documents_pkey PRIMARY KEY (id),
  CONSTRAINT broker_documents_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.broker_profiles(id),
  CONSTRAINT broker_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.broker_payouts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  broker_id uuid NOT NULL,
  shipment_id uuid NOT NULL,
  assignment_id uuid,
  payout_status text DEFAULT 'pending'::text CHECK (payout_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'disputed'::text])),
  payout_amount numeric NOT NULL,
  commission_rate numeric NOT NULL,
  payment_method text CHECK (payment_method = ANY (ARRAY['stripe_transfer'::text, 'ach'::text, 'wire'::text, 'check'::text, 'paypal'::text])),
  stripe_transfer_id text,
  transaction_id text,
  eligible_for_payout_at timestamp with time zone,
  processed_at timestamp with time zone,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  disputed_at timestamp with time zone,
  dispute_reason text,
  dispute_resolved_at timestamp with time zone,
  dispute_resolution text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT broker_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT broker_payouts_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.broker_profiles(id),
  CONSTRAINT broker_payouts_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT broker_payouts_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.broker_assignments(id)
);
CREATE TABLE public.broker_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL UNIQUE,
  company_name text NOT NULL,
  dba_name text,
  company_email text NOT NULL,
  company_phone text NOT NULL,
  dot_number text UNIQUE,
  mc_number text UNIQUE,
  tax_id text,
  broker_license_number text,
  insurance_policy_number text,
  insurance_provider text,
  insurance_amount numeric,
  insurance_expiry_date date,
  bond_number text,
  bond_amount numeric,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'documents_submitted'::text, 'under_review'::text, 'verified'::text, 'rejected'::text, 'suspended'::text])),
  fmcsa_verified boolean DEFAULT false,
  dot_verified boolean DEFAULT false,
  insurance_verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  verification_notes text,
  business_structure text CHECK (business_structure = ANY (ARRAY['sole_proprietorship'::text, 'llc'::text, 'corporation'::text, 's_corp'::text, 'partnership'::text])),
  years_in_business integer,
  website_url text,
  business_address text NOT NULL,
  business_city text NOT NULL,
  business_state text NOT NULL,
  business_zip text NOT NULL,
  business_country text DEFAULT 'USA'::text,
  default_commission_rate numeric DEFAULT 25.00,
  platform_fee_rate numeric DEFAULT 10.00,
  total_shipments_completed integer DEFAULT 0,
  total_revenue_generated numeric DEFAULT 0,
  average_rating numeric DEFAULT 0,
  total_ratings integer DEFAULT 0,
  on_time_delivery_rate numeric DEFAULT 0,
  cancellation_rate numeric DEFAULT 0,
  total_carriers integer DEFAULT 0,
  active_carriers integer DEFAULT 0,
  account_status text DEFAULT 'active'::text CHECK (account_status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text, 'closed'::text])),
  suspension_reason text,
  suspended_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT broker_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT broker_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.broker_shipments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  broker_id uuid NOT NULL,
  client_name text NOT NULL,
  client_email text NOT NULL,
  client_phone text NOT NULL,
  pickup_address text NOT NULL,
  pickup_city text NOT NULL,
  pickup_state text NOT NULL,
  pickup_zip text NOT NULL,
  pickup_latitude numeric,
  pickup_longitude numeric,
  delivery_address text NOT NULL,
  delivery_city text NOT NULL,
  delivery_state text NOT NULL,
  delivery_zip text NOT NULL,
  delivery_latitude numeric,
  delivery_longitude numeric,
  vehicle_year integer NOT NULL,
  vehicle_make text NOT NULL,
  vehicle_model text NOT NULL,
  vehicle_type text NOT NULL,
  vehicle_condition text NOT NULL DEFAULT 'running'::text,
  vehicle_vin text,
  distance_miles numeric NOT NULL DEFAULT 0,
  estimated_price numeric NOT NULL,
  broker_commission numeric NOT NULL DEFAULT 0,
  platform_fee numeric NOT NULL DEFAULT 0,
  pickup_date date,
  delivery_date date,
  transport_type text NOT NULL DEFAULT 'open'::text,
  is_operable boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'pending_quote'::text,
  load_board_id uuid,
  assigned_carrier_id uuid,
  notes text,
  special_instructions text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  booked_at timestamp with time zone,
  assigned_at timestamp with time zone,
  picked_up_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT broker_shipments_pkey PRIMARY KEY (id),
  CONSTRAINT broker_shipments_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES auth.users(id),
  CONSTRAINT broker_shipments_load_board_id_fkey FOREIGN KEY (load_board_id) REFERENCES public.load_board(id),
  CONSTRAINT broker_shipments_assigned_carrier_id_fkey FOREIGN KEY (assigned_carrier_id) REFERENCES auth.users(id)
);
CREATE TABLE public.cancellation_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  cancelled_by uuid NOT NULL,
  canceller_role text NOT NULL CHECK (canceller_role = ANY (ARRAY['client'::text, 'driver'::text, 'admin'::text])),
  cancellation_type text NOT NULL CHECK (cancellation_type = ANY (ARRAY['before_driver_accepts'::text, 'after_accept_before_arrival'::text, 'at_pickup_mismatch'::text, 'at_pickup_fraud'::text, 'in_transit_emergency'::text, 'admin_intervention'::text])),
  cancellation_stage text NOT NULL CHECK (cancellation_stage = ANY (ARRAY['pending'::text, 'accepted'::text, 'en_route'::text, 'arrived'::text, 'pickup_verified'::text, 'picked_up'::text, 'in_transit'::text, 'delivered'::text])),
  reason_category text NOT NULL CHECK (reason_category = ANY (ARRAY['vehicle_mismatch'::text, 'not_drivable'::text, 'significant_damage'::text, 'wrong_vehicle'::text, 'safety_concern'::text, 'client_fraud'::text, 'driver_no_show'::text, 'client_request'::text, 'emergency'::text, 'other'::text])),
  reason_description text NOT NULL,
  evidence_photos jsonb DEFAULT '[]'::jsonb,
  pickup_verification_id uuid,
  original_amount numeric NOT NULL,
  client_refund_amount numeric NOT NULL DEFAULT 0,
  driver_compensation_amount numeric NOT NULL DEFAULT 0,
  platform_fee_amount numeric NOT NULL DEFAULT 0,
  refund_status text NOT NULL DEFAULT 'pending'::text CHECK (refund_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  refund_processed_at timestamp with time zone,
  refund_transaction_id text,
  payment_status_before_cancel text,
  requires_admin_review boolean DEFAULT false,
  admin_reviewed boolean DEFAULT false,
  admin_reviewer_id uuid,
  admin_notes text,
  reviewed_at timestamp with time zone,
  fraud_confirmed boolean DEFAULT false,
  user_banned boolean DEFAULT false,
  cancelled_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cancellation_records_pkey PRIMARY KEY (id),
  CONSTRAINT cancellation_records_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT cancellation_records_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id),
  CONSTRAINT cancellation_records_pickup_verification_id_fkey FOREIGN KEY (pickup_verification_id) REFERENCES public.pickup_verifications(id),
  CONSTRAINT cancellation_records_admin_reviewer_id_fkey FOREIGN KEY (admin_reviewer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.client_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  label text NOT NULL,
  street_address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  zip_code text NOT NULL,
  country text DEFAULT 'United States'::text,
  is_default boolean DEFAULT false,
  is_pickup_location boolean DEFAULT true,
  is_delivery_location boolean DEFAULT true,
  contact_name text,
  contact_phone text,
  special_instructions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT client_addresses_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.client_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['credit_card'::text, 'debit_card'::text, 'bank_account'::text, 'paypal'::text])),
  provider text NOT NULL,
  provider_payment_method_id text NOT NULL,
  last_four text,
  card_brand text,
  expiry_month integer,
  expiry_year integer,
  is_default boolean DEFAULT false,
  billing_address jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT client_payment_methods_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.client_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL UNIQUE,
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  marketing_emails boolean DEFAULT false,
  auto_quotes boolean DEFAULT true,
  preferred_communication text DEFAULT 'email'::text CHECK (preferred_communication = ANY (ARRAY['email'::text, 'sms'::text, 'push'::text])),
  quote_notifications boolean DEFAULT true,
  shipment_updates boolean DEFAULT true,
  promotional_offers boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT client_settings_pkey PRIMARY KEY (id),
  CONSTRAINT client_settings_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT conversations_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT conversations_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.driver_applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  full_name text NOT NULL,
  date_of_birth date NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  address jsonb NOT NULL,
  ssn_encrypted text NOT NULL,
  license_number text NOT NULL,
  license_state text NOT NULL,
  license_expiration date NOT NULL,
  license_front_url text,
  license_back_url text,
  proof_of_address_url text,
  has_suspensions boolean DEFAULT false,
  has_criminal_record boolean DEFAULT false,
  incident_description text,
  insurance_provider text NOT NULL,
  insurance_policy_number text NOT NULL,
  insurance_expiration date NOT NULL,
  insurance_proof_url text,
  coverage_amount text NOT NULL,
  background_check_consent boolean NOT NULL DEFAULT false,
  data_use_consent boolean NOT NULL DEFAULT false,
  insurance_consent boolean NOT NULL DEFAULT false,
  terms_accepted boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending'::text,
  rejection_reason text,
  background_check_status text,
  background_check_report_id text,
  background_check_completed_at timestamp with time zone,
  background_check_result jsonb,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  approval_notes text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  admin_comment text,
  CONSTRAINT driver_applications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.driver_locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  heading double precision,
  speed double precision,
  accuracy double precision,
  location_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT driver_locations_pkey PRIMARY KEY (id),
  CONSTRAINT driver_locations_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT driver_locations_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.driver_privacy_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL UNIQUE,
  share_location_with_customers boolean DEFAULT true,
  share_phone_with_customers boolean DEFAULT false,
  allow_rating_and_reviews boolean DEFAULT true,
  data_retention_period text DEFAULT '2years'::text CHECK (data_retention_period = ANY (ARRAY['1year'::text, '2years'::text, '5years'::text, 'indefinite'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_privacy_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT driver_privacy_preferences_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.driver_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL UNIQUE,
  driver_id uuid NOT NULL,
  client_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT driver_ratings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT driver_ratings_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT driver_ratings_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.driver_security_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL UNIQUE,
  two_factor_enabled boolean DEFAULT false,
  biometric_enabled boolean DEFAULT false,
  location_sharing_enabled boolean DEFAULT true,
  data_analytics_enabled boolean DEFAULT true,
  marketing_emails_enabled boolean DEFAULT false,
  push_notifications_enabled boolean DEFAULT true,
  emergency_contacts_enabled boolean DEFAULT true,
  trip_history_visibility text DEFAULT 'limited'::text CHECK (trip_history_visibility = ANY (ARRAY['public'::text, 'limited'::text, 'private'::text])),
  profile_visibility text DEFAULT 'limited'::text CHECK (profile_visibility = ANY (ARRAY['public'::text, 'limited'::text, 'private'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_security_settings_pkey PRIMARY KEY (id),
  CONSTRAINT driver_security_settings_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.driver_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL UNIQUE,
  available_for_jobs boolean DEFAULT true,
  notifications_enabled boolean DEFAULT true,
  preferred_radius integer DEFAULT 50,
  allow_location_tracking boolean DEFAULT true,
  preferred_job_types ARRAY DEFAULT ARRAY['standard'::text, 'express'::text],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_settings_pkey PRIMARY KEY (id),
  CONSTRAINT driver_settings_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  make text NOT NULL,
  model text NOT NULL,
  year integer NOT NULL,
  color text NOT NULL,
  license_plate text NOT NULL,
  vehicle_type text DEFAULT 'standard'::text CHECK (vehicle_type = ANY (ARRAY['standard'::text, 'large'::text, 'refrigerated'::text, 'hazmat'::text])),
  capacity_weight numeric,
  capacity_volume numeric,
  insurance_provider text,
  insurance_policy_number text,
  insurance_expiry_date date,
  registration_number text,
  registration_expiry_date date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT driver_vehicles_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.job_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])),
  applied_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_applications_pkey PRIMARY KEY (id),
  CONSTRAINT job_applications_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT job_applications_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.load_board (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL UNIQUE,
  posted_by uuid NOT NULL,
  visibility text DEFAULT 'public'::text CHECK (visibility = ANY (ARRAY['public'::text, 'invited_only'::text, 'network_only'::text])),
  allowed_brokers ARRAY,
  load_status text DEFAULT 'available'::text CHECK (load_status = ANY (ARRAY['available'::text, 'pending_acceptance'::text, 'assigned'::text, 'cancelled'::text, 'expired'::text])),
  expires_at timestamp with time zone,
  bidding_enabled boolean DEFAULT true,
  reserve_price numeric,
  current_best_bid_id uuid,
  total_bids integer DEFAULT 0,
  suggested_carrier_payout numeric,
  max_broker_commission numeric,
  assigned_to_broker_id uuid,
  assigned_to_carrier_id uuid,
  assigned_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT load_board_pkey PRIMARY KEY (id),
  CONSTRAINT load_board_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT load_board_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.profiles(id),
  CONSTRAINT load_board_assigned_to_broker_id_fkey FOREIGN KEY (assigned_to_broker_id) REFERENCES public.broker_profiles(id),
  CONSTRAINT load_board_assigned_to_carrier_id_fkey FOREIGN KEY (assigned_to_carrier_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.load_board_bids (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  load_board_id uuid NOT NULL,
  broker_id uuid NOT NULL,
  carrier_id uuid NOT NULL,
  broker_carrier_relationship_id uuid,
  bid_status text DEFAULT 'pending'::text CHECK (bid_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'withdrawn'::text, 'expired'::text])),
  carrier_payout numeric NOT NULL,
  broker_commission numeric NOT NULL,
  total_cost numeric NOT NULL,
  platform_fee numeric NOT NULL,
  commission_rate numeric NOT NULL,
  carrier_name text NOT NULL,
  carrier_rating numeric,
  carrier_completed_shipments integer,
  estimated_pickup_date date,
  estimated_delivery_date date,
  bid_notes text,
  expires_at timestamp with time zone,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  rejection_reason text,
  withdrawn_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT load_board_bids_pkey PRIMARY KEY (id),
  CONSTRAINT load_board_bids_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.broker_profiles(id),
  CONSTRAINT load_board_bids_carrier_id_fkey FOREIGN KEY (carrier_id) REFERENCES public.profiles(id),
  CONSTRAINT load_board_bids_broker_carrier_relationship_id_fkey FOREIGN KEY (broker_carrier_relationship_id) REFERENCES public.broker_carriers(id),
  CONSTRAINT load_board_bids_load_board_id_fkey FOREIGN KEY (load_board_id) REFERENCES public.load_board(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  content text NOT NULL CHECK (char_length(content) <= 5000),
  message_type text NOT NULL DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'system'::text, 'notification'::text])),
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.profiles(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
  CONSTRAINT messages_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  push_notifications boolean NOT NULL DEFAULT true,
  email_notifications boolean NOT NULL DEFAULT true,
  sms_notifications boolean NOT NULL DEFAULT false,
  shipment_updates boolean NOT NULL DEFAULT true,
  driver_assigned boolean NOT NULL DEFAULT true,
  payment_updates boolean NOT NULL DEFAULT true,
  promotions boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  messages boolean DEFAULT true,
  delivery_completed boolean DEFAULT true,
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['payment'::text, 'payment_success'::text, 'payment_failed'::text, 'shipment_created'::text, 'shipment_updated'::text, 'driver_assigned'::text, 'delivery_completed'::text, 'message_received'::text, 'system'::text])),
  title text NOT NULL,
  message text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payment_receipts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  receipt_number character varying NOT NULL UNIQUE,
  receipt_type character varying NOT NULL CHECK (receipt_type::text = ANY (ARRAY['upfront'::character varying, 'final'::character varying, 'refund'::character varying]::text[])),
  amount numeric NOT NULL,
  sent_to_email character varying NOT NULL,
  email_status character varying DEFAULT 'sent'::character varying CHECK (email_status::text = ANY (ARRAY['sent'::character varying, 'delivered'::character varying, 'failed'::character varying, 'bounced'::character varying]::text[])),
  sent_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT payment_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT payment_receipts_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  client_id uuid NOT NULL,
  amount numeric NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  payment_method text,
  payment_intent_id text,
  payment_intent_client_secret text,
  refund_id text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  initial_amount integer,
  remaining_amount integer,
  booking_timestamp timestamp with time zone,
  refund_deadline timestamp with time zone,
  is_refundable boolean DEFAULT true,
  payment_type character varying DEFAULT 'initial'::character varying,
  parent_payment_id uuid,
  payment_distribution jsonb DEFAULT '{}'::jsonb,
  carrier_payout_status text DEFAULT 'pending'::text CHECK (carrier_payout_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  broker_payout_status text DEFAULT 'pending'::text CHECK (broker_payout_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  carrier_payout_date timestamp with time zone,
  broker_payout_date timestamp with time zone,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_parent_payment_id_fkey FOREIGN KEY (parent_payment_id) REFERENCES public.payments(id),
  CONSTRAINT payments_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.pickup_verifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL UNIQUE,
  driver_id uuid NOT NULL,
  pickup_location USER-DEFINED NOT NULL,
  pickup_address_verified boolean NOT NULL DEFAULT false,
  gps_accuracy_meters numeric,
  distance_from_address_meters numeric,
  driver_photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  client_photos_reference jsonb NOT NULL DEFAULT '[]'::jsonb,
  comparison_notes jsonb DEFAULT '{}'::jsonb,
  verification_status text NOT NULL CHECK (verification_status = ANY (ARRAY['matches'::text, 'minor_differences'::text, 'major_issues'::text, 'pending'::text])),
  differences_description text,
  cannot_proceed_reason text CHECK (cannot_proceed_reason = ANY (ARRAY['not_drivable'::text, 'significant_damage'::text, 'wrong_vehicle'::text, 'safety_concern'::text, 'vehicle_missing'::text, 'other'::text])),
  client_notified_at timestamp with time zone,
  client_response text CHECK (client_response = ANY (ARRAY['approved'::text, 'disputed'::text, 'no_response'::text, NULL::text])),
  client_response_notes text,
  client_responded_at timestamp with time zone,
  arrival_time timestamp with time zone NOT NULL DEFAULT now(),
  verification_started_at timestamp with time zone,
  verification_completed_at timestamp with time zone,
  app_version text,
  device_info jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pickup_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT pickup_verifications_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT pickup_verifications_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.pricing_config (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  min_quote numeric NOT NULL DEFAULT 150.00,
  accident_min_quote numeric NOT NULL DEFAULT 80.00,
  min_miles integer NOT NULL DEFAULT 100,
  base_fuel_price numeric NOT NULL DEFAULT 3.70,
  current_fuel_price numeric NOT NULL DEFAULT 3.70,
  fuel_adjustment_per_dollar numeric NOT NULL DEFAULT 5.00,
  surge_multiplier numeric NOT NULL DEFAULT 1.00,
  surge_enabled boolean NOT NULL DEFAULT false,
  surge_reason text,
  expedited_multiplier numeric NOT NULL DEFAULT 1.25,
  standard_multiplier numeric NOT NULL DEFAULT 1.00,
  flexible_multiplier numeric NOT NULL DEFAULT 0.95,
  short_distance_max integer NOT NULL DEFAULT 500,
  mid_distance_max integer NOT NULL DEFAULT 1500,
  bulk_discount_enabled boolean NOT NULL DEFAULT true,
  expedited_service_enabled boolean NOT NULL DEFAULT true,
  flexible_service_enabled boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  notes text,
  CONSTRAINT pricing_config_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_config_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pricing_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pricing_config_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  config_id uuid,
  config_snapshot jsonb NOT NULL,
  changed_by uuid,
  change_reason text,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  changed_fields ARRAY,
  CONSTRAINT pricing_config_history_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_config_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id),
  CONSTRAINT pricing_config_history_config_id_fkey FOREIGN KEY (config_id) REFERENCES public.pricing_config(id)
);
CREATE TABLE public.privacy_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  location_tracking boolean DEFAULT true,
  share_profile boolean DEFAULT false,
  show_online_status boolean DEFAULT true,
  allow_analytics boolean DEFAULT true,
  two_factor_auth boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT privacy_settings_pkey PRIMARY KEY (id),
  CONSTRAINT privacy_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text,
  avatar_url text,
  role USER-DEFINED NOT NULL DEFAULT 'client'::user_role,
  is_verified boolean NOT NULL DEFAULT false,
  rating numeric CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  notifications_last_viewed_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.push_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token text NOT NULL,
  device_type text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.shipment_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  status USER-DEFINED NOT NULL,
  changed_by uuid NOT NULL,
  changed_at timestamp with time zone DEFAULT now(),
  notes text,
  location_lat numeric,
  location_lng numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipment_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id),
  CONSTRAINT shipment_status_history_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.shipments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  driver_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::shipment_status,
  title text NOT NULL,
  description text,
  pickup_address text NOT NULL,
  pickup_location USER-DEFINED,
  pickup_notes text,
  pickup_time_window tstzrange,
  delivery_address text NOT NULL,
  delivery_location USER-DEFINED,
  delivery_notes text,
  delivery_time_window tstzrange,
  weight_kg numeric,
  dimensions_cm jsonb,
  item_value numeric,
  is_fragile boolean DEFAULT false,
  estimated_distance_km numeric,
  estimated_price numeric NOT NULL,
  final_price numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  pickup_date timestamp with time zone,
  delivery_date timestamp with time zone,
  pickup_city text,
  pickup_state text,
  pickup_zip text,
  delivery_city text,
  delivery_state text,
  delivery_zip text,
  vehicle_type text,
  cargo_type text,
  distance numeric,
  price numeric,
  weight numeric,
  dimensions text,
  updated_by uuid,
  payment_status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  vehicle_make text,
  vehicle_model text,
  vehicle_year integer,
  is_operable boolean DEFAULT true,
  payment_intent_id text,
  terms_accepted boolean DEFAULT false,
  vehicle_count integer DEFAULT 1,
  is_accident_recovery boolean DEFAULT false,
  driver_arrival_time timestamp with time zone,
  pickup_verified boolean DEFAULT false,
  pickup_verified_at timestamp with time zone,
  pickup_verification_status text CHECK (pickup_verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'issues_reported'::text, 'cancelled'::text])),
  actual_pickup_time timestamp with time zone,
  estimated_delivery_time timestamp with time zone,
  actual_delivery_time timestamp with time zone,
  delivery_verified boolean DEFAULT false,
  delivery_photos jsonb DEFAULT '[]'::jsonb,
  cancellation_record_id uuid,
  client_vehicle_photos jsonb DEFAULT '{"left": [], "rear": [], "front": [], "right": [], "damage": [], "interior": []}'::jsonb,
  delivery_confirmation_photos jsonb DEFAULT '[]'::jsonb,
  upfront_payment_sent boolean DEFAULT false,
  final_receipt_sent boolean DEFAULT false,
  driver_payout_notified boolean DEFAULT false,
  broker_id uuid,
  broker_carrier_id uuid,
  broker_commission_rate numeric DEFAULT 0,
  carrier_payout_amount numeric DEFAULT 0,
  broker_payout_amount numeric DEFAULT 0,
  is_broker_shipment boolean DEFAULT false,
  assignment_type text DEFAULT 'direct'::text CHECK (assignment_type = ANY (ARRAY['direct'::text, 'broker_assigned'::text, 'load_board'::text])),
  CONSTRAINT shipments_pkey PRIMARY KEY (id),
  CONSTRAINT shipments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT shipments_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT shipments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT shipments_cancellation_record_id_fkey FOREIGN KEY (cancellation_record_id) REFERENCES public.cancellation_records(id),
  CONSTRAINT shipments_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.profiles(id),
  CONSTRAINT shipments_broker_carrier_id_fkey FOREIGN KEY (broker_carrier_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['technical'::text, 'account'::text, 'payment'::text, 'general'::text])),
  priority text NOT NULL CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tracking_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shipment_id uuid NOT NULL,
  event_type USER-DEFINED NOT NULL,
  created_by uuid NOT NULL,
  location USER-DEFINED,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracking_events_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT tracking_events_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.user_onboarding (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  dashboard_tour_completed boolean DEFAULT false,
  shipment_creation_tour_completed boolean DEFAULT false,
  tracking_tour_completed boolean DEFAULT false,
  payment_tour_completed boolean DEFAULT false,
  admin_tour_completed boolean DEFAULT false,
  broker_tour_completed boolean DEFAULT false,
  driver_tour_completed boolean DEFAULT false,
  checklist_progress jsonb DEFAULT '{"profile_completed": false, "documents_uploaded": false, "payment_method_added": false, "first_shipment_created": false, "first_shipment_tracked": false}'::jsonb,
  dismissed_hints ARRAY DEFAULT ARRAY[]::text[],
  show_tours boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_onboarding_pkey PRIMARY KEY (id),
  CONSTRAINT user_onboarding_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_vehicles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  vehicle_type USER-DEFINED NOT NULL,
  make text NOT NULL,
  model text NOT NULL,
  year integer NOT NULL CHECK (year >= 1900 AND year::numeric <= (EXTRACT(year FROM now()) + 2::numeric)),
  color text,
  license_plate text CHECK (license_plate IS NULL OR length(license_plate) >= 2 AND length(license_plate) <= 15),
  nickname text,
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT user_vehicles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);